/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.4.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QLineEdit *lineEdit_10;
    QLineEdit *lineEdit_20;
    QLineEdit *lineEdit_30;
    QLineEdit *lineEdit_40;
    QLineEdit *lineEdit_50;
    QLineEdit *lineEdit_60;
    QLineEdit *lineEdit_70;
    QLineEdit *lineEdit_80;
    QLineEdit *lineEdit_90;
    QLineEdit *lineEdit_110;
    QLineEdit *lineEdit_120;
    QLineEdit *lineEdit_150;
    QLineEdit *lineEdit_170;
    QLineEdit *lineEdit_140;
    QLineEdit *lineEdit_130;
    QLineEdit *lineEdit_100;
    QLineEdit *lineEdit_160;
    QLineEdit *lineEdit_180;
    QLineEdit *lineEdit_280;
    QLineEdit *lineEdit_240;
    QLineEdit *lineEdit_350;
    QLineEdit *lineEdit_320;
    QLineEdit *lineEdit_260;
    QLineEdit *lineEdit_330;
    QLineEdit *lineEdit_190;
    QLineEdit *lineEdit_220;
    QLineEdit *lineEdit_290;
    QLineEdit *lineEdit_340;
    QLineEdit *lineEdit_250;
    QLineEdit *lineEdit_300;
    QLineEdit *lineEdit_210;
    QLineEdit *lineEdit_200;
    QLineEdit *lineEdit_230;
    QLineEdit *lineEdit_310;
    QLineEdit *lineEdit_270;
    QLineEdit *lineEdit_360;
    QLineEdit *lineEdit_810;
    QLineEdit *lineEdit_660;
    QLineEdit *lineEdit_410;
    QLineEdit *lineEdit_520;
    QLineEdit *lineEdit_490;
    QLineEdit *lineEdit_690;
    QLineEdit *lineEdit_430;
    QLineEdit *lineEdit_500;
    QLineEdit *lineEdit_450;
    QLineEdit *lineEdit_700;
    QLineEdit *lineEdit_560;
    QLineEdit *lineEdit_680;
    QLineEdit *lineEdit_580;
    QLineEdit *lineEdit_390;
    QLineEdit *lineEdit_710;
    QLineEdit *lineEdit_460;
    QLineEdit *lineEdit_600;
    QLineEdit *lineEdit_630;
    QLineEdit *lineEdit_570;
    QLineEdit *lineEdit_550;
    QLineEdit *lineEdit_510;
    QLineEdit *lineEdit_420;
    QLineEdit *lineEdit_590;
    QLineEdit *lineEdit_620;
    QLineEdit *lineEdit_470;
    QLineEdit *lineEdit_380;
    QLineEdit *lineEdit_370;
    QLineEdit *lineEdit_640;
    QLineEdit *lineEdit_670;
    QLineEdit *lineEdit_400;
    QLineEdit *lineEdit_610;
    QLineEdit *lineEdit_480;
    QLineEdit *lineEdit_440;
    QLineEdit *lineEdit_530;
    QLineEdit *lineEdit_650;
    QLineEdit *lineEdit_540;
    QLineEdit *lineEdit_780;
    QLineEdit *lineEdit_720;
    QLineEdit *lineEdit_800;
    QLineEdit *lineEdit_760;
    QLineEdit *lineEdit_750;
    QLineEdit *lineEdit_740;
    QLineEdit *lineEdit_790;
    QLineEdit *lineEdit_770;
    QLineEdit *lineEdit_730;
    QLabel *label;
    QPushButton *go_pushbutton;
    QLineEdit *lineEdit_221;
    QLineEdit *lineEdit_731;
    QLineEdit *lineEdit_61;
    QLineEdit *lineEdit_391;
    QLineEdit *lineEdit_681;
    QLineEdit *lineEdit_461;
    QLineEdit *lineEdit_541;
    QLineEdit *lineEdit_801;
    QLineEdit *lineEdit_701;
    QLineEdit *lineEdit_671;
    QLineEdit *lineEdit_781;
    QLineEdit *lineEdit_151;
    QLineEdit *lineEdit_401;
    QLineEdit *lineEdit_601;
    QLineEdit *lineEdit_491;
    QLineEdit *lineEdit_341;
    QLineEdit *lineEdit_451;
    QLineEdit *lineEdit_711;
    QLineEdit *lineEdit_241;
    QLineEdit *lineEdit_431;
    QLineEdit *lineEdit_441;
    QLineEdit *lineEdit_71;
    QLineEdit *lineEdit_521;
    QLineEdit *lineEdit_31;
    QLineEdit *lineEdit_381;
    QLineEdit *lineEdit_371;
    QLineEdit *lineEdit_771;
    QLineEdit *lineEdit_471;
    QLineEdit *lineEdit_201;
    QLineEdit *lineEdit_661;
    QLineEdit *lineEdit_181;
    QLineEdit *lineEdit_691;
    QLineEdit *lineEdit_641;
    QLineEdit *lineEdit_191;
    QLineEdit *lineEdit_291;
    QLineEdit *lineEdit_331;
    QLineEdit *lineEdit_51;
    QLineEdit *lineEdit_41;
    QLineEdit *lineEdit_311;
    QLineEdit *lineEdit_251;
    QLineEdit *lineEdit_591;
    QLineEdit *lineEdit_21;
    QLineEdit *lineEdit_271;
    QLineEdit *lineEdit_551;
    QLineEdit *lineEdit_811;
    QLineEdit *lineEdit_761;
    QLineEdit *lineEdit_501;
    QLineEdit *lineEdit_351;
    QLineEdit *lineEdit_101;
    QLineEdit *lineEdit_321;
    QLineEdit *lineEdit_741;
    QLineEdit *lineEdit_411;
    QLineEdit *lineEdit_91;
    QLineEdit *lineEdit_261;
    QLineEdit *lineEdit_231;
    QLineEdit *lineEdit_631;
    QLineEdit *lineEdit_511;
    QLineEdit *lineEdit_581;
    QLineEdit *lineEdit_211;
    QLineEdit *lineEdit_571;
    QLineEdit *lineEdit_561;
    QLineEdit *lineEdit_751;
    QLineEdit *lineEdit_171;
    QLineEdit *lineEdit_11;
    QLineEdit *lineEdit_81;
    QLineEdit *lineEdit_161;
    QLineEdit *lineEdit_651;
    QLineEdit *lineEdit_611;
    QLineEdit *lineEdit_421;
    QLineEdit *lineEdit_361;
    QLineEdit *lineEdit_131;
    QLineEdit *lineEdit_621;
    QLineEdit *lineEdit_121;
    QLineEdit *lineEdit_281;
    QLineEdit *lineEdit_141;
    QLineEdit *lineEdit_481;
    QLineEdit *lineEdit_301;
    QLineEdit *lineEdit_111;
    QLineEdit *lineEdit_531;
    QLineEdit *lineEdit_791;
    QLineEdit *lineEdit_721;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_4;
    QPushButton *pushButton;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;
    QToolBar *toolBar;
    QToolBar *toolBar_2;
    QToolBar *toolBar_3;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(1007, 659);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        lineEdit_10 = new QLineEdit(centralWidget);
        lineEdit_10->setObjectName(QStringLiteral("lineEdit_10"));
        lineEdit_10->setGeometry(QRect(80, 140, 31, 27));
        lineEdit_10->setLayoutDirection(Qt::RightToLeft);
        lineEdit_10->setMaxLength(1);
        lineEdit_10->setReadOnly(false);
        lineEdit_20 = new QLineEdit(centralWidget);
        lineEdit_20->setObjectName(QStringLiteral("lineEdit_20"));
        lineEdit_20->setGeometry(QRect(110, 140, 31, 27));
        lineEdit_20->setLayoutDirection(Qt::RightToLeft);
        lineEdit_20->setMaxLength(1);
        lineEdit_30 = new QLineEdit(centralWidget);
        lineEdit_30->setObjectName(QStringLiteral("lineEdit_30"));
        lineEdit_30->setGeometry(QRect(140, 140, 31, 27));
        lineEdit_30->setLayoutDirection(Qt::RightToLeft);
        lineEdit_30->setMaxLength(1);
        lineEdit_40 = new QLineEdit(centralWidget);
        lineEdit_40->setObjectName(QStringLiteral("lineEdit_40"));
        lineEdit_40->setGeometry(QRect(180, 140, 31, 27));
        lineEdit_40->setLayoutDirection(Qt::RightToLeft);
        lineEdit_40->setMaxLength(1);
        lineEdit_50 = new QLineEdit(centralWidget);
        lineEdit_50->setObjectName(QStringLiteral("lineEdit_50"));
        lineEdit_50->setGeometry(QRect(210, 140, 31, 27));
        lineEdit_50->setLayoutDirection(Qt::RightToLeft);
        lineEdit_50->setMaxLength(1);
        lineEdit_60 = new QLineEdit(centralWidget);
        lineEdit_60->setObjectName(QStringLiteral("lineEdit_60"));
        lineEdit_60->setGeometry(QRect(240, 140, 31, 27));
        lineEdit_60->setLayoutDirection(Qt::RightToLeft);
        lineEdit_60->setMaxLength(1);
        lineEdit_70 = new QLineEdit(centralWidget);
        lineEdit_70->setObjectName(QStringLiteral("lineEdit_70"));
        lineEdit_70->setGeometry(QRect(280, 140, 31, 27));
        lineEdit_70->setLayoutDirection(Qt::RightToLeft);
        lineEdit_70->setMaxLength(1);
        lineEdit_80 = new QLineEdit(centralWidget);
        lineEdit_80->setObjectName(QStringLiteral("lineEdit_80"));
        lineEdit_80->setGeometry(QRect(310, 140, 31, 27));
        lineEdit_80->setLayoutDirection(Qt::RightToLeft);
        lineEdit_80->setMaxLength(1);
        lineEdit_90 = new QLineEdit(centralWidget);
        lineEdit_90->setObjectName(QStringLiteral("lineEdit_90"));
        lineEdit_90->setGeometry(QRect(340, 140, 31, 27));
        lineEdit_90->setLayoutDirection(Qt::RightToLeft);
        lineEdit_90->setMaxLength(1);
        lineEdit_110 = new QLineEdit(centralWidget);
        lineEdit_110->setObjectName(QStringLiteral("lineEdit_110"));
        lineEdit_110->setGeometry(QRect(110, 170, 31, 27));
        lineEdit_110->setLayoutDirection(Qt::RightToLeft);
        lineEdit_110->setMaxLength(1);
        lineEdit_120 = new QLineEdit(centralWidget);
        lineEdit_120->setObjectName(QStringLiteral("lineEdit_120"));
        lineEdit_120->setGeometry(QRect(140, 170, 31, 27));
        lineEdit_120->setLayoutDirection(Qt::RightToLeft);
        lineEdit_120->setMaxLength(1);
        lineEdit_150 = new QLineEdit(centralWidget);
        lineEdit_150->setObjectName(QStringLiteral("lineEdit_150"));
        lineEdit_150->setGeometry(QRect(240, 170, 31, 27));
        lineEdit_150->setLayoutDirection(Qt::RightToLeft);
        lineEdit_150->setMaxLength(1);
        lineEdit_170 = new QLineEdit(centralWidget);
        lineEdit_170->setObjectName(QStringLiteral("lineEdit_170"));
        lineEdit_170->setGeometry(QRect(310, 170, 31, 27));
        lineEdit_170->setLayoutDirection(Qt::RightToLeft);
        lineEdit_170->setMaxLength(1);
        lineEdit_140 = new QLineEdit(centralWidget);
        lineEdit_140->setObjectName(QStringLiteral("lineEdit_140"));
        lineEdit_140->setGeometry(QRect(210, 170, 31, 27));
        lineEdit_140->setLayoutDirection(Qt::RightToLeft);
        lineEdit_140->setMaxLength(1);
        lineEdit_130 = new QLineEdit(centralWidget);
        lineEdit_130->setObjectName(QStringLiteral("lineEdit_130"));
        lineEdit_130->setGeometry(QRect(180, 170, 31, 27));
        lineEdit_130->setLayoutDirection(Qt::RightToLeft);
        lineEdit_130->setMaxLength(1);
        lineEdit_100 = new QLineEdit(centralWidget);
        lineEdit_100->setObjectName(QStringLiteral("lineEdit_100"));
        lineEdit_100->setGeometry(QRect(80, 170, 31, 27));
        lineEdit_100->setLayoutDirection(Qt::RightToLeft);
        lineEdit_100->setMaxLength(1);
        lineEdit_160 = new QLineEdit(centralWidget);
        lineEdit_160->setObjectName(QStringLiteral("lineEdit_160"));
        lineEdit_160->setGeometry(QRect(280, 170, 31, 27));
        lineEdit_160->setLayoutDirection(Qt::RightToLeft);
        lineEdit_160->setMaxLength(1);
        lineEdit_180 = new QLineEdit(centralWidget);
        lineEdit_180->setObjectName(QStringLiteral("lineEdit_180"));
        lineEdit_180->setGeometry(QRect(340, 170, 31, 27));
        lineEdit_180->setLayoutDirection(Qt::RightToLeft);
        lineEdit_180->setMaxLength(1);
        lineEdit_280 = new QLineEdit(centralWidget);
        lineEdit_280->setObjectName(QStringLiteral("lineEdit_280"));
        lineEdit_280->setGeometry(QRect(80, 240, 31, 27));
        lineEdit_280->setLayoutDirection(Qt::RightToLeft);
        lineEdit_280->setMaxLength(1);
        lineEdit_240 = new QLineEdit(centralWidget);
        lineEdit_240->setObjectName(QStringLiteral("lineEdit_240"));
        lineEdit_240->setGeometry(QRect(240, 200, 31, 27));
        lineEdit_240->setLayoutDirection(Qt::RightToLeft);
        lineEdit_240->setMaxLength(1);
        lineEdit_350 = new QLineEdit(centralWidget);
        lineEdit_350->setObjectName(QStringLiteral("lineEdit_350"));
        lineEdit_350->setGeometry(QRect(310, 240, 31, 27));
        lineEdit_350->setLayoutDirection(Qt::RightToLeft);
        lineEdit_350->setMaxLength(1);
        lineEdit_320 = new QLineEdit(centralWidget);
        lineEdit_320->setObjectName(QStringLiteral("lineEdit_320"));
        lineEdit_320->setGeometry(QRect(210, 240, 31, 27));
        lineEdit_320->setLayoutDirection(Qt::RightToLeft);
        lineEdit_320->setMaxLength(1);
        lineEdit_260 = new QLineEdit(centralWidget);
        lineEdit_260->setObjectName(QStringLiteral("lineEdit_260"));
        lineEdit_260->setGeometry(QRect(310, 200, 31, 27));
        lineEdit_260->setLayoutDirection(Qt::RightToLeft);
        lineEdit_260->setMaxLength(1);
        lineEdit_330 = new QLineEdit(centralWidget);
        lineEdit_330->setObjectName(QStringLiteral("lineEdit_330"));
        lineEdit_330->setGeometry(QRect(240, 240, 31, 27));
        lineEdit_330->setLayoutDirection(Qt::RightToLeft);
        lineEdit_330->setMaxLength(1);
        lineEdit_190 = new QLineEdit(centralWidget);
        lineEdit_190->setObjectName(QStringLiteral("lineEdit_190"));
        lineEdit_190->setGeometry(QRect(80, 200, 31, 27));
        lineEdit_190->setLayoutDirection(Qt::RightToLeft);
        lineEdit_190->setMaxLength(1);
        lineEdit_220 = new QLineEdit(centralWidget);
        lineEdit_220->setObjectName(QStringLiteral("lineEdit_220"));
        lineEdit_220->setGeometry(QRect(180, 200, 31, 27));
        lineEdit_220->setLayoutDirection(Qt::RightToLeft);
        lineEdit_220->setMaxLength(1);
        lineEdit_290 = new QLineEdit(centralWidget);
        lineEdit_290->setObjectName(QStringLiteral("lineEdit_290"));
        lineEdit_290->setGeometry(QRect(110, 240, 31, 27));
        lineEdit_290->setLayoutDirection(Qt::RightToLeft);
        lineEdit_290->setMaxLength(1);
        lineEdit_340 = new QLineEdit(centralWidget);
        lineEdit_340->setObjectName(QStringLiteral("lineEdit_340"));
        lineEdit_340->setGeometry(QRect(280, 240, 31, 27));
        lineEdit_340->setLayoutDirection(Qt::RightToLeft);
        lineEdit_340->setMaxLength(1);
        lineEdit_250 = new QLineEdit(centralWidget);
        lineEdit_250->setObjectName(QStringLiteral("lineEdit_250"));
        lineEdit_250->setGeometry(QRect(280, 200, 31, 27));
        lineEdit_250->setLayoutDirection(Qt::RightToLeft);
        lineEdit_250->setMaxLength(1);
        lineEdit_300 = new QLineEdit(centralWidget);
        lineEdit_300->setObjectName(QStringLiteral("lineEdit_300"));
        lineEdit_300->setGeometry(QRect(140, 240, 31, 27));
        lineEdit_300->setLayoutDirection(Qt::RightToLeft);
        lineEdit_300->setMaxLength(1);
        lineEdit_210 = new QLineEdit(centralWidget);
        lineEdit_210->setObjectName(QStringLiteral("lineEdit_210"));
        lineEdit_210->setGeometry(QRect(140, 200, 31, 27));
        lineEdit_210->setLayoutDirection(Qt::RightToLeft);
        lineEdit_210->setMaxLength(1);
        lineEdit_200 = new QLineEdit(centralWidget);
        lineEdit_200->setObjectName(QStringLiteral("lineEdit_200"));
        lineEdit_200->setGeometry(QRect(110, 200, 31, 27));
        lineEdit_200->setLayoutDirection(Qt::RightToLeft);
        lineEdit_200->setMaxLength(1);
        lineEdit_230 = new QLineEdit(centralWidget);
        lineEdit_230->setObjectName(QStringLiteral("lineEdit_230"));
        lineEdit_230->setGeometry(QRect(210, 200, 31, 27));
        lineEdit_230->setLayoutDirection(Qt::RightToLeft);
        lineEdit_230->setMaxLength(1);
        lineEdit_310 = new QLineEdit(centralWidget);
        lineEdit_310->setObjectName(QStringLiteral("lineEdit_310"));
        lineEdit_310->setGeometry(QRect(180, 240, 31, 27));
        lineEdit_310->setLayoutDirection(Qt::RightToLeft);
        lineEdit_310->setMaxLength(1);
        lineEdit_270 = new QLineEdit(centralWidget);
        lineEdit_270->setObjectName(QStringLiteral("lineEdit_270"));
        lineEdit_270->setGeometry(QRect(340, 200, 31, 27));
        lineEdit_270->setLayoutDirection(Qt::RightToLeft);
        lineEdit_270->setMaxLength(1);
        lineEdit_360 = new QLineEdit(centralWidget);
        lineEdit_360->setObjectName(QStringLiteral("lineEdit_360"));
        lineEdit_360->setGeometry(QRect(340, 240, 31, 27));
        lineEdit_360->setLayoutDirection(Qt::RightToLeft);
        lineEdit_360->setMaxLength(1);
        lineEdit_810 = new QLineEdit(centralWidget);
        lineEdit_810->setObjectName(QStringLiteral("lineEdit_810"));
        lineEdit_810->setGeometry(QRect(340, 400, 31, 27));
        lineEdit_810->setLayoutDirection(Qt::RightToLeft);
        lineEdit_810->setMaxLength(1);
        lineEdit_660 = new QLineEdit(centralWidget);
        lineEdit_660->setObjectName(QStringLiteral("lineEdit_660"));
        lineEdit_660->setGeometry(QRect(140, 370, 31, 27));
        lineEdit_660->setLayoutDirection(Qt::RightToLeft);
        lineEdit_660->setMaxLength(1);
        lineEdit_410 = new QLineEdit(centralWidget);
        lineEdit_410->setObjectName(QStringLiteral("lineEdit_410"));
        lineEdit_410->setGeometry(QRect(210, 270, 31, 27));
        lineEdit_410->setLayoutDirection(Qt::RightToLeft);
        lineEdit_410->setMaxLength(1);
        lineEdit_520 = new QLineEdit(centralWidget);
        lineEdit_520->setObjectName(QStringLiteral("lineEdit_520"));
        lineEdit_520->setGeometry(QRect(280, 300, 31, 27));
        lineEdit_520->setLayoutDirection(Qt::RightToLeft);
        lineEdit_520->setMaxLength(1);
        lineEdit_490 = new QLineEdit(centralWidget);
        lineEdit_490->setObjectName(QStringLiteral("lineEdit_490"));
        lineEdit_490->setGeometry(QRect(180, 300, 31, 27));
        lineEdit_490->setLayoutDirection(Qt::RightToLeft);
        lineEdit_490->setMaxLength(1);
        lineEdit_690 = new QLineEdit(centralWidget);
        lineEdit_690->setObjectName(QStringLiteral("lineEdit_690"));
        lineEdit_690->setGeometry(QRect(240, 370, 31, 27));
        lineEdit_690->setLayoutDirection(Qt::RightToLeft);
        lineEdit_690->setMaxLength(1);
        lineEdit_430 = new QLineEdit(centralWidget);
        lineEdit_430->setObjectName(QStringLiteral("lineEdit_430"));
        lineEdit_430->setGeometry(QRect(280, 270, 31, 27));
        lineEdit_430->setLayoutDirection(Qt::RightToLeft);
        lineEdit_430->setMaxLength(1);
        lineEdit_500 = new QLineEdit(centralWidget);
        lineEdit_500->setObjectName(QStringLiteral("lineEdit_500"));
        lineEdit_500->setGeometry(QRect(210, 300, 31, 27));
        lineEdit_500->setLayoutDirection(Qt::RightToLeft);
        lineEdit_500->setMaxLength(1);
        lineEdit_450 = new QLineEdit(centralWidget);
        lineEdit_450->setObjectName(QStringLiteral("lineEdit_450"));
        lineEdit_450->setGeometry(QRect(340, 270, 31, 27));
        lineEdit_450->setLayoutDirection(Qt::RightToLeft);
        lineEdit_450->setMaxLength(1);
        lineEdit_700 = new QLineEdit(centralWidget);
        lineEdit_700->setObjectName(QStringLiteral("lineEdit_700"));
        lineEdit_700->setGeometry(QRect(280, 370, 31, 27));
        lineEdit_700->setLayoutDirection(Qt::RightToLeft);
        lineEdit_700->setMaxLength(1);
        lineEdit_560 = new QLineEdit(centralWidget);
        lineEdit_560->setObjectName(QStringLiteral("lineEdit_560"));
        lineEdit_560->setGeometry(QRect(110, 340, 31, 27));
        lineEdit_560->setLayoutDirection(Qt::RightToLeft);
        lineEdit_560->setMaxLength(1);
        lineEdit_680 = new QLineEdit(centralWidget);
        lineEdit_680->setObjectName(QStringLiteral("lineEdit_680"));
        lineEdit_680->setGeometry(QRect(210, 370, 31, 27));
        lineEdit_680->setLayoutDirection(Qt::RightToLeft);
        lineEdit_680->setMaxLength(1);
        lineEdit_580 = new QLineEdit(centralWidget);
        lineEdit_580->setObjectName(QStringLiteral("lineEdit_580"));
        lineEdit_580->setGeometry(QRect(180, 340, 31, 27));
        lineEdit_580->setLayoutDirection(Qt::RightToLeft);
        lineEdit_580->setMaxLength(1);
        lineEdit_390 = new QLineEdit(centralWidget);
        lineEdit_390->setObjectName(QStringLiteral("lineEdit_390"));
        lineEdit_390->setGeometry(QRect(140, 270, 31, 27));
        lineEdit_390->setLayoutDirection(Qt::RightToLeft);
        lineEdit_390->setMaxLength(1);
        lineEdit_710 = new QLineEdit(centralWidget);
        lineEdit_710->setObjectName(QStringLiteral("lineEdit_710"));
        lineEdit_710->setGeometry(QRect(310, 370, 31, 27));
        lineEdit_710->setLayoutDirection(Qt::RightToLeft);
        lineEdit_710->setMaxLength(1);
        lineEdit_460 = new QLineEdit(centralWidget);
        lineEdit_460->setObjectName(QStringLiteral("lineEdit_460"));
        lineEdit_460->setGeometry(QRect(80, 300, 31, 27));
        lineEdit_460->setLayoutDirection(Qt::RightToLeft);
        lineEdit_460->setMaxLength(1);
        lineEdit_600 = new QLineEdit(centralWidget);
        lineEdit_600->setObjectName(QStringLiteral("lineEdit_600"));
        lineEdit_600->setGeometry(QRect(240, 340, 31, 27));
        lineEdit_600->setLayoutDirection(Qt::RightToLeft);
        lineEdit_600->setMaxLength(1);
        lineEdit_630 = new QLineEdit(centralWidget);
        lineEdit_630->setObjectName(QStringLiteral("lineEdit_630"));
        lineEdit_630->setGeometry(QRect(340, 340, 31, 27));
        lineEdit_630->setLayoutDirection(Qt::RightToLeft);
        lineEdit_630->setMaxLength(1);
        lineEdit_570 = new QLineEdit(centralWidget);
        lineEdit_570->setObjectName(QStringLiteral("lineEdit_570"));
        lineEdit_570->setGeometry(QRect(140, 340, 31, 27));
        lineEdit_570->setLayoutDirection(Qt::RightToLeft);
        lineEdit_570->setMaxLength(1);
        lineEdit_550 = new QLineEdit(centralWidget);
        lineEdit_550->setObjectName(QStringLiteral("lineEdit_550"));
        lineEdit_550->setGeometry(QRect(80, 340, 31, 27));
        lineEdit_550->setLayoutDirection(Qt::RightToLeft);
        lineEdit_550->setMaxLength(1);
        lineEdit_510 = new QLineEdit(centralWidget);
        lineEdit_510->setObjectName(QStringLiteral("lineEdit_510"));
        lineEdit_510->setGeometry(QRect(240, 300, 31, 27));
        lineEdit_510->setLayoutDirection(Qt::RightToLeft);
        lineEdit_510->setMaxLength(1);
        lineEdit_420 = new QLineEdit(centralWidget);
        lineEdit_420->setObjectName(QStringLiteral("lineEdit_420"));
        lineEdit_420->setGeometry(QRect(240, 270, 31, 27));
        lineEdit_420->setLayoutDirection(Qt::RightToLeft);
        lineEdit_420->setMaxLength(1);
        lineEdit_590 = new QLineEdit(centralWidget);
        lineEdit_590->setObjectName(QStringLiteral("lineEdit_590"));
        lineEdit_590->setGeometry(QRect(210, 340, 31, 27));
        lineEdit_590->setLayoutDirection(Qt::RightToLeft);
        lineEdit_590->setMaxLength(1);
        lineEdit_620 = new QLineEdit(centralWidget);
        lineEdit_620->setObjectName(QStringLiteral("lineEdit_620"));
        lineEdit_620->setGeometry(QRect(310, 340, 31, 27));
        lineEdit_620->setLayoutDirection(Qt::RightToLeft);
        lineEdit_620->setMaxLength(1);
        lineEdit_470 = new QLineEdit(centralWidget);
        lineEdit_470->setObjectName(QStringLiteral("lineEdit_470"));
        lineEdit_470->setGeometry(QRect(110, 300, 31, 27));
        lineEdit_470->setLayoutDirection(Qt::RightToLeft);
        lineEdit_470->setMaxLength(1);
        lineEdit_380 = new QLineEdit(centralWidget);
        lineEdit_380->setObjectName(QStringLiteral("lineEdit_380"));
        lineEdit_380->setGeometry(QRect(110, 270, 31, 27));
        lineEdit_380->setLayoutDirection(Qt::RightToLeft);
        lineEdit_380->setMaxLength(1);
        lineEdit_370 = new QLineEdit(centralWidget);
        lineEdit_370->setObjectName(QStringLiteral("lineEdit_370"));
        lineEdit_370->setGeometry(QRect(80, 270, 31, 27));
        lineEdit_370->setLayoutDirection(Qt::RightToLeft);
        lineEdit_370->setMaxLength(1);
        lineEdit_640 = new QLineEdit(centralWidget);
        lineEdit_640->setObjectName(QStringLiteral("lineEdit_640"));
        lineEdit_640->setGeometry(QRect(80, 370, 31, 27));
        lineEdit_640->setLayoutDirection(Qt::RightToLeft);
        lineEdit_640->setMaxLength(1);
        lineEdit_670 = new QLineEdit(centralWidget);
        lineEdit_670->setObjectName(QStringLiteral("lineEdit_670"));
        lineEdit_670->setGeometry(QRect(180, 370, 31, 27));
        lineEdit_670->setLayoutDirection(Qt::RightToLeft);
        lineEdit_670->setMaxLength(1);
        lineEdit_400 = new QLineEdit(centralWidget);
        lineEdit_400->setObjectName(QStringLiteral("lineEdit_400"));
        lineEdit_400->setGeometry(QRect(180, 270, 31, 27));
        lineEdit_400->setLayoutDirection(Qt::RightToLeft);
        lineEdit_400->setMaxLength(1);
        lineEdit_610 = new QLineEdit(centralWidget);
        lineEdit_610->setObjectName(QStringLiteral("lineEdit_610"));
        lineEdit_610->setGeometry(QRect(280, 340, 31, 27));
        lineEdit_610->setLayoutDirection(Qt::RightToLeft);
        lineEdit_610->setMaxLength(1);
        lineEdit_480 = new QLineEdit(centralWidget);
        lineEdit_480->setObjectName(QStringLiteral("lineEdit_480"));
        lineEdit_480->setGeometry(QRect(140, 300, 31, 27));
        lineEdit_480->setLayoutDirection(Qt::RightToLeft);
        lineEdit_480->setMaxLength(1);
        lineEdit_440 = new QLineEdit(centralWidget);
        lineEdit_440->setObjectName(QStringLiteral("lineEdit_440"));
        lineEdit_440->setGeometry(QRect(310, 270, 31, 27));
        lineEdit_440->setLayoutDirection(Qt::RightToLeft);
        lineEdit_440->setMaxLength(1);
        lineEdit_530 = new QLineEdit(centralWidget);
        lineEdit_530->setObjectName(QStringLiteral("lineEdit_530"));
        lineEdit_530->setGeometry(QRect(310, 300, 31, 27));
        lineEdit_530->setLayoutDirection(Qt::RightToLeft);
        lineEdit_530->setMaxLength(1);
        lineEdit_650 = new QLineEdit(centralWidget);
        lineEdit_650->setObjectName(QStringLiteral("lineEdit_650"));
        lineEdit_650->setGeometry(QRect(110, 370, 31, 27));
        lineEdit_650->setLayoutDirection(Qt::RightToLeft);
        lineEdit_650->setMaxLength(1);
        lineEdit_540 = new QLineEdit(centralWidget);
        lineEdit_540->setObjectName(QStringLiteral("lineEdit_540"));
        lineEdit_540->setGeometry(QRect(340, 300, 31, 27));
        lineEdit_540->setLayoutDirection(Qt::RightToLeft);
        lineEdit_540->setMaxLength(1);
        lineEdit_780 = new QLineEdit(centralWidget);
        lineEdit_780->setObjectName(QStringLiteral("lineEdit_780"));
        lineEdit_780->setGeometry(QRect(240, 400, 31, 27));
        lineEdit_780->setLayoutDirection(Qt::RightToLeft);
        lineEdit_780->setMaxLength(1);
        lineEdit_720 = new QLineEdit(centralWidget);
        lineEdit_720->setObjectName(QStringLiteral("lineEdit_720"));
        lineEdit_720->setGeometry(QRect(340, 370, 31, 27));
        lineEdit_720->setLayoutDirection(Qt::RightToLeft);
        lineEdit_720->setMaxLength(1);
        lineEdit_800 = new QLineEdit(centralWidget);
        lineEdit_800->setObjectName(QStringLiteral("lineEdit_800"));
        lineEdit_800->setGeometry(QRect(310, 400, 31, 27));
        lineEdit_800->setLayoutDirection(Qt::RightToLeft);
        lineEdit_800->setMaxLength(1);
        lineEdit_760 = new QLineEdit(centralWidget);
        lineEdit_760->setObjectName(QStringLiteral("lineEdit_760"));
        lineEdit_760->setGeometry(QRect(180, 400, 31, 27));
        lineEdit_760->setLayoutDirection(Qt::RightToLeft);
        lineEdit_760->setMaxLength(1);
        lineEdit_750 = new QLineEdit(centralWidget);
        lineEdit_750->setObjectName(QStringLiteral("lineEdit_750"));
        lineEdit_750->setGeometry(QRect(140, 400, 31, 27));
        lineEdit_750->setLayoutDirection(Qt::RightToLeft);
        lineEdit_750->setMaxLength(1);
        lineEdit_740 = new QLineEdit(centralWidget);
        lineEdit_740->setObjectName(QStringLiteral("lineEdit_740"));
        lineEdit_740->setGeometry(QRect(110, 400, 31, 27));
        lineEdit_740->setLayoutDirection(Qt::RightToLeft);
        lineEdit_740->setMaxLength(1);
        lineEdit_790 = new QLineEdit(centralWidget);
        lineEdit_790->setObjectName(QStringLiteral("lineEdit_790"));
        lineEdit_790->setGeometry(QRect(280, 400, 31, 27));
        lineEdit_790->setLayoutDirection(Qt::RightToLeft);
        lineEdit_790->setMaxLength(1);
        lineEdit_770 = new QLineEdit(centralWidget);
        lineEdit_770->setObjectName(QStringLiteral("lineEdit_770"));
        lineEdit_770->setGeometry(QRect(210, 400, 31, 27));
        lineEdit_770->setLayoutDirection(Qt::RightToLeft);
        lineEdit_770->setMaxLength(1);
        lineEdit_730 = new QLineEdit(centralWidget);
        lineEdit_730->setObjectName(QStringLiteral("lineEdit_730"));
        lineEdit_730->setGeometry(QRect(80, 400, 31, 27));
        lineEdit_730->setLayoutDirection(Qt::RightToLeft);
        lineEdit_730->setMaxLength(1);
        label = new QLabel(centralWidget);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(190, 100, 71, 21));
        label->setFrameShape(QFrame::WinPanel);
        go_pushbutton = new QPushButton(centralWidget);
        go_pushbutton->setObjectName(QStringLiteral("go_pushbutton"));
        go_pushbutton->setGeometry(QRect(450, 460, 99, 27));
        lineEdit_221 = new QLineEdit(centralWidget);
        lineEdit_221->setObjectName(QStringLiteral("lineEdit_221"));
        lineEdit_221->setGeometry(QRect(740, 200, 31, 27));
        lineEdit_221->setLayoutDirection(Qt::RightToLeft);
        lineEdit_221->setMaxLength(1);
        lineEdit_221->setReadOnly(true);
        lineEdit_731 = new QLineEdit(centralWidget);
        lineEdit_731->setObjectName(QStringLiteral("lineEdit_731"));
        lineEdit_731->setGeometry(QRect(640, 400, 31, 27));
        lineEdit_731->setLayoutDirection(Qt::RightToLeft);
        lineEdit_731->setMaxLength(1);
        lineEdit_731->setReadOnly(true);
        lineEdit_61 = new QLineEdit(centralWidget);
        lineEdit_61->setObjectName(QStringLiteral("lineEdit_61"));
        lineEdit_61->setGeometry(QRect(800, 140, 31, 27));
        lineEdit_61->setLayoutDirection(Qt::RightToLeft);
        lineEdit_61->setMaxLength(1);
        lineEdit_61->setReadOnly(true);
        lineEdit_391 = new QLineEdit(centralWidget);
        lineEdit_391->setObjectName(QStringLiteral("lineEdit_391"));
        lineEdit_391->setGeometry(QRect(700, 270, 31, 27));
        lineEdit_391->setLayoutDirection(Qt::RightToLeft);
        lineEdit_391->setMaxLength(1);
        lineEdit_391->setReadOnly(true);
        lineEdit_681 = new QLineEdit(centralWidget);
        lineEdit_681->setObjectName(QStringLiteral("lineEdit_681"));
        lineEdit_681->setGeometry(QRect(770, 370, 31, 27));
        lineEdit_681->setLayoutDirection(Qt::RightToLeft);
        lineEdit_681->setMaxLength(1);
        lineEdit_681->setReadOnly(true);
        lineEdit_461 = new QLineEdit(centralWidget);
        lineEdit_461->setObjectName(QStringLiteral("lineEdit_461"));
        lineEdit_461->setGeometry(QRect(640, 300, 31, 27));
        lineEdit_461->setLayoutDirection(Qt::RightToLeft);
        lineEdit_461->setMaxLength(1);
        lineEdit_461->setReadOnly(true);
        lineEdit_541 = new QLineEdit(centralWidget);
        lineEdit_541->setObjectName(QStringLiteral("lineEdit_541"));
        lineEdit_541->setGeometry(QRect(900, 300, 31, 27));
        lineEdit_541->setLayoutDirection(Qt::RightToLeft);
        lineEdit_541->setMaxLength(1);
        lineEdit_541->setReadOnly(true);
        lineEdit_801 = new QLineEdit(centralWidget);
        lineEdit_801->setObjectName(QStringLiteral("lineEdit_801"));
        lineEdit_801->setGeometry(QRect(870, 400, 31, 27));
        lineEdit_801->setLayoutDirection(Qt::RightToLeft);
        lineEdit_801->setMaxLength(1);
        lineEdit_801->setReadOnly(true);
        lineEdit_701 = new QLineEdit(centralWidget);
        lineEdit_701->setObjectName(QStringLiteral("lineEdit_701"));
        lineEdit_701->setGeometry(QRect(840, 370, 31, 27));
        lineEdit_701->setLayoutDirection(Qt::RightToLeft);
        lineEdit_701->setMaxLength(1);
        lineEdit_701->setReadOnly(true);
        lineEdit_671 = new QLineEdit(centralWidget);
        lineEdit_671->setObjectName(QStringLiteral("lineEdit_671"));
        lineEdit_671->setGeometry(QRect(740, 370, 31, 27));
        lineEdit_671->setLayoutDirection(Qt::RightToLeft);
        lineEdit_671->setMaxLength(1);
        lineEdit_671->setReadOnly(true);
        lineEdit_781 = new QLineEdit(centralWidget);
        lineEdit_781->setObjectName(QStringLiteral("lineEdit_781"));
        lineEdit_781->setGeometry(QRect(800, 400, 31, 27));
        lineEdit_781->setLayoutDirection(Qt::RightToLeft);
        lineEdit_781->setMaxLength(1);
        lineEdit_781->setReadOnly(true);
        lineEdit_151 = new QLineEdit(centralWidget);
        lineEdit_151->setObjectName(QStringLiteral("lineEdit_151"));
        lineEdit_151->setGeometry(QRect(800, 170, 31, 27));
        lineEdit_151->setLayoutDirection(Qt::RightToLeft);
        lineEdit_151->setMaxLength(1);
        lineEdit_151->setReadOnly(true);
        lineEdit_401 = new QLineEdit(centralWidget);
        lineEdit_401->setObjectName(QStringLiteral("lineEdit_401"));
        lineEdit_401->setGeometry(QRect(740, 270, 31, 27));
        lineEdit_401->setLayoutDirection(Qt::RightToLeft);
        lineEdit_401->setMaxLength(1);
        lineEdit_401->setReadOnly(true);
        lineEdit_601 = new QLineEdit(centralWidget);
        lineEdit_601->setObjectName(QStringLiteral("lineEdit_601"));
        lineEdit_601->setGeometry(QRect(800, 340, 31, 27));
        lineEdit_601->setLayoutDirection(Qt::RightToLeft);
        lineEdit_601->setMaxLength(1);
        lineEdit_601->setReadOnly(true);
        lineEdit_491 = new QLineEdit(centralWidget);
        lineEdit_491->setObjectName(QStringLiteral("lineEdit_491"));
        lineEdit_491->setGeometry(QRect(740, 300, 31, 27));
        lineEdit_491->setLayoutDirection(Qt::RightToLeft);
        lineEdit_491->setMaxLength(1);
        lineEdit_491->setReadOnly(true);
        lineEdit_341 = new QLineEdit(centralWidget);
        lineEdit_341->setObjectName(QStringLiteral("lineEdit_341"));
        lineEdit_341->setGeometry(QRect(840, 240, 31, 27));
        lineEdit_341->setLayoutDirection(Qt::RightToLeft);
        lineEdit_341->setMaxLength(1);
        lineEdit_341->setReadOnly(true);
        lineEdit_451 = new QLineEdit(centralWidget);
        lineEdit_451->setObjectName(QStringLiteral("lineEdit_451"));
        lineEdit_451->setGeometry(QRect(900, 270, 31, 27));
        lineEdit_451->setLayoutDirection(Qt::RightToLeft);
        lineEdit_451->setMaxLength(1);
        lineEdit_451->setReadOnly(true);
        lineEdit_711 = new QLineEdit(centralWidget);
        lineEdit_711->setObjectName(QStringLiteral("lineEdit_711"));
        lineEdit_711->setGeometry(QRect(870, 370, 31, 27));
        lineEdit_711->setLayoutDirection(Qt::RightToLeft);
        lineEdit_711->setMaxLength(1);
        lineEdit_711->setReadOnly(true);
        lineEdit_241 = new QLineEdit(centralWidget);
        lineEdit_241->setObjectName(QStringLiteral("lineEdit_241"));
        lineEdit_241->setGeometry(QRect(800, 200, 31, 27));
        lineEdit_241->setLayoutDirection(Qt::RightToLeft);
        lineEdit_241->setMaxLength(1);
        lineEdit_241->setReadOnly(true);
        lineEdit_431 = new QLineEdit(centralWidget);
        lineEdit_431->setObjectName(QStringLiteral("lineEdit_431"));
        lineEdit_431->setGeometry(QRect(840, 270, 31, 27));
        lineEdit_431->setLayoutDirection(Qt::RightToLeft);
        lineEdit_431->setMaxLength(1);
        lineEdit_431->setReadOnly(true);
        lineEdit_441 = new QLineEdit(centralWidget);
        lineEdit_441->setObjectName(QStringLiteral("lineEdit_441"));
        lineEdit_441->setGeometry(QRect(870, 270, 31, 27));
        lineEdit_441->setLayoutDirection(Qt::RightToLeft);
        lineEdit_441->setMaxLength(1);
        lineEdit_441->setReadOnly(true);
        lineEdit_71 = new QLineEdit(centralWidget);
        lineEdit_71->setObjectName(QStringLiteral("lineEdit_71"));
        lineEdit_71->setGeometry(QRect(840, 140, 31, 27));
        lineEdit_71->setLayoutDirection(Qt::RightToLeft);
        lineEdit_71->setMaxLength(1);
        lineEdit_71->setReadOnly(true);
        lineEdit_521 = new QLineEdit(centralWidget);
        lineEdit_521->setObjectName(QStringLiteral("lineEdit_521"));
        lineEdit_521->setGeometry(QRect(840, 300, 31, 27));
        lineEdit_521->setLayoutDirection(Qt::RightToLeft);
        lineEdit_521->setMaxLength(1);
        lineEdit_521->setReadOnly(true);
        lineEdit_31 = new QLineEdit(centralWidget);
        lineEdit_31->setObjectName(QStringLiteral("lineEdit_31"));
        lineEdit_31->setGeometry(QRect(700, 140, 31, 27));
        lineEdit_31->setLayoutDirection(Qt::RightToLeft);
        lineEdit_31->setMaxLength(1);
        lineEdit_31->setReadOnly(true);
        lineEdit_381 = new QLineEdit(centralWidget);
        lineEdit_381->setObjectName(QStringLiteral("lineEdit_381"));
        lineEdit_381->setGeometry(QRect(670, 270, 31, 27));
        lineEdit_381->setLayoutDirection(Qt::RightToLeft);
        lineEdit_381->setMaxLength(1);
        lineEdit_381->setReadOnly(true);
        lineEdit_371 = new QLineEdit(centralWidget);
        lineEdit_371->setObjectName(QStringLiteral("lineEdit_371"));
        lineEdit_371->setGeometry(QRect(640, 270, 31, 27));
        lineEdit_371->setLayoutDirection(Qt::RightToLeft);
        lineEdit_371->setMaxLength(1);
        lineEdit_371->setReadOnly(true);
        lineEdit_771 = new QLineEdit(centralWidget);
        lineEdit_771->setObjectName(QStringLiteral("lineEdit_771"));
        lineEdit_771->setGeometry(QRect(770, 400, 31, 27));
        lineEdit_771->setLayoutDirection(Qt::RightToLeft);
        lineEdit_771->setMaxLength(1);
        lineEdit_771->setReadOnly(true);
        lineEdit_471 = new QLineEdit(centralWidget);
        lineEdit_471->setObjectName(QStringLiteral("lineEdit_471"));
        lineEdit_471->setGeometry(QRect(670, 300, 31, 27));
        lineEdit_471->setLayoutDirection(Qt::RightToLeft);
        lineEdit_471->setMaxLength(1);
        lineEdit_471->setReadOnly(true);
        lineEdit_201 = new QLineEdit(centralWidget);
        lineEdit_201->setObjectName(QStringLiteral("lineEdit_201"));
        lineEdit_201->setGeometry(QRect(670, 200, 31, 27));
        lineEdit_201->setLayoutDirection(Qt::RightToLeft);
        lineEdit_201->setMaxLength(1);
        lineEdit_201->setReadOnly(true);
        lineEdit_661 = new QLineEdit(centralWidget);
        lineEdit_661->setObjectName(QStringLiteral("lineEdit_661"));
        lineEdit_661->setGeometry(QRect(700, 370, 31, 27));
        lineEdit_661->setLayoutDirection(Qt::RightToLeft);
        lineEdit_661->setMaxLength(1);
        lineEdit_661->setReadOnly(true);
        lineEdit_181 = new QLineEdit(centralWidget);
        lineEdit_181->setObjectName(QStringLiteral("lineEdit_181"));
        lineEdit_181->setGeometry(QRect(900, 170, 31, 27));
        lineEdit_181->setLayoutDirection(Qt::RightToLeft);
        lineEdit_181->setMaxLength(1);
        lineEdit_181->setReadOnly(true);
        lineEdit_691 = new QLineEdit(centralWidget);
        lineEdit_691->setObjectName(QStringLiteral("lineEdit_691"));
        lineEdit_691->setGeometry(QRect(800, 370, 31, 27));
        lineEdit_691->setLayoutDirection(Qt::RightToLeft);
        lineEdit_691->setMaxLength(1);
        lineEdit_691->setReadOnly(true);
        lineEdit_641 = new QLineEdit(centralWidget);
        lineEdit_641->setObjectName(QStringLiteral("lineEdit_641"));
        lineEdit_641->setGeometry(QRect(640, 370, 31, 27));
        lineEdit_641->setLayoutDirection(Qt::RightToLeft);
        lineEdit_641->setMaxLength(1);
        lineEdit_641->setReadOnly(true);
        lineEdit_191 = new QLineEdit(centralWidget);
        lineEdit_191->setObjectName(QStringLiteral("lineEdit_191"));
        lineEdit_191->setGeometry(QRect(640, 200, 31, 27));
        lineEdit_191->setLayoutDirection(Qt::RightToLeft);
        lineEdit_191->setMaxLength(1);
        lineEdit_191->setReadOnly(true);
        lineEdit_291 = new QLineEdit(centralWidget);
        lineEdit_291->setObjectName(QStringLiteral("lineEdit_291"));
        lineEdit_291->setGeometry(QRect(670, 240, 31, 27));
        lineEdit_291->setLayoutDirection(Qt::RightToLeft);
        lineEdit_291->setMaxLength(1);
        lineEdit_291->setReadOnly(true);
        lineEdit_331 = new QLineEdit(centralWidget);
        lineEdit_331->setObjectName(QStringLiteral("lineEdit_331"));
        lineEdit_331->setGeometry(QRect(800, 240, 31, 27));
        lineEdit_331->setLayoutDirection(Qt::RightToLeft);
        lineEdit_331->setMaxLength(1);
        lineEdit_331->setReadOnly(true);
        lineEdit_51 = new QLineEdit(centralWidget);
        lineEdit_51->setObjectName(QStringLiteral("lineEdit_51"));
        lineEdit_51->setGeometry(QRect(770, 140, 31, 27));
        lineEdit_51->setLayoutDirection(Qt::RightToLeft);
        lineEdit_51->setMaxLength(1);
        lineEdit_51->setReadOnly(true);
        lineEdit_41 = new QLineEdit(centralWidget);
        lineEdit_41->setObjectName(QStringLiteral("lineEdit_41"));
        lineEdit_41->setGeometry(QRect(740, 140, 31, 27));
        lineEdit_41->setLayoutDirection(Qt::RightToLeft);
        lineEdit_41->setMaxLength(1);
        lineEdit_41->setReadOnly(true);
        lineEdit_311 = new QLineEdit(centralWidget);
        lineEdit_311->setObjectName(QStringLiteral("lineEdit_311"));
        lineEdit_311->setGeometry(QRect(740, 240, 31, 27));
        lineEdit_311->setLayoutDirection(Qt::RightToLeft);
        lineEdit_311->setMaxLength(1);
        lineEdit_311->setReadOnly(true);
        lineEdit_251 = new QLineEdit(centralWidget);
        lineEdit_251->setObjectName(QStringLiteral("lineEdit_251"));
        lineEdit_251->setGeometry(QRect(840, 200, 31, 27));
        lineEdit_251->setLayoutDirection(Qt::RightToLeft);
        lineEdit_251->setMaxLength(1);
        lineEdit_251->setReadOnly(true);
        lineEdit_591 = new QLineEdit(centralWidget);
        lineEdit_591->setObjectName(QStringLiteral("lineEdit_591"));
        lineEdit_591->setGeometry(QRect(770, 340, 31, 27));
        lineEdit_591->setLayoutDirection(Qt::RightToLeft);
        lineEdit_591->setMaxLength(1);
        lineEdit_591->setReadOnly(true);
        lineEdit_21 = new QLineEdit(centralWidget);
        lineEdit_21->setObjectName(QStringLiteral("lineEdit_21"));
        lineEdit_21->setGeometry(QRect(670, 140, 31, 27));
        lineEdit_21->setLayoutDirection(Qt::RightToLeft);
        lineEdit_21->setMaxLength(1);
        lineEdit_21->setReadOnly(true);
        lineEdit_271 = new QLineEdit(centralWidget);
        lineEdit_271->setObjectName(QStringLiteral("lineEdit_271"));
        lineEdit_271->setGeometry(QRect(900, 200, 31, 27));
        lineEdit_271->setLayoutDirection(Qt::RightToLeft);
        lineEdit_271->setMaxLength(1);
        lineEdit_271->setReadOnly(true);
        lineEdit_551 = new QLineEdit(centralWidget);
        lineEdit_551->setObjectName(QStringLiteral("lineEdit_551"));
        lineEdit_551->setGeometry(QRect(640, 340, 31, 27));
        lineEdit_551->setLayoutDirection(Qt::RightToLeft);
        lineEdit_551->setMaxLength(1);
        lineEdit_551->setReadOnly(true);
        lineEdit_811 = new QLineEdit(centralWidget);
        lineEdit_811->setObjectName(QStringLiteral("lineEdit_811"));
        lineEdit_811->setGeometry(QRect(900, 400, 31, 27));
        lineEdit_811->setLayoutDirection(Qt::RightToLeft);
        lineEdit_811->setMaxLength(1);
        lineEdit_811->setReadOnly(true);
        lineEdit_761 = new QLineEdit(centralWidget);
        lineEdit_761->setObjectName(QStringLiteral("lineEdit_761"));
        lineEdit_761->setGeometry(QRect(740, 400, 31, 27));
        lineEdit_761->setLayoutDirection(Qt::RightToLeft);
        lineEdit_761->setMaxLength(1);
        lineEdit_761->setReadOnly(true);
        lineEdit_501 = new QLineEdit(centralWidget);
        lineEdit_501->setObjectName(QStringLiteral("lineEdit_501"));
        lineEdit_501->setGeometry(QRect(770, 300, 31, 27));
        lineEdit_501->setLayoutDirection(Qt::RightToLeft);
        lineEdit_501->setMaxLength(1);
        lineEdit_501->setReadOnly(true);
        lineEdit_351 = new QLineEdit(centralWidget);
        lineEdit_351->setObjectName(QStringLiteral("lineEdit_351"));
        lineEdit_351->setGeometry(QRect(870, 240, 31, 27));
        lineEdit_351->setLayoutDirection(Qt::RightToLeft);
        lineEdit_351->setMaxLength(1);
        lineEdit_351->setReadOnly(true);
        lineEdit_101 = new QLineEdit(centralWidget);
        lineEdit_101->setObjectName(QStringLiteral("lineEdit_101"));
        lineEdit_101->setGeometry(QRect(640, 170, 31, 27));
        lineEdit_101->setLayoutDirection(Qt::RightToLeft);
        lineEdit_101->setMaxLength(1);
        lineEdit_101->setReadOnly(true);
        lineEdit_321 = new QLineEdit(centralWidget);
        lineEdit_321->setObjectName(QStringLiteral("lineEdit_321"));
        lineEdit_321->setGeometry(QRect(770, 240, 31, 27));
        lineEdit_321->setLayoutDirection(Qt::RightToLeft);
        lineEdit_321->setMaxLength(1);
        lineEdit_321->setReadOnly(true);
        lineEdit_741 = new QLineEdit(centralWidget);
        lineEdit_741->setObjectName(QStringLiteral("lineEdit_741"));
        lineEdit_741->setGeometry(QRect(670, 400, 31, 27));
        lineEdit_741->setLayoutDirection(Qt::RightToLeft);
        lineEdit_741->setMaxLength(1);
        lineEdit_741->setReadOnly(true);
        lineEdit_411 = new QLineEdit(centralWidget);
        lineEdit_411->setObjectName(QStringLiteral("lineEdit_411"));
        lineEdit_411->setGeometry(QRect(770, 270, 31, 27));
        lineEdit_411->setLayoutDirection(Qt::RightToLeft);
        lineEdit_411->setMaxLength(1);
        lineEdit_411->setReadOnly(true);
        lineEdit_91 = new QLineEdit(centralWidget);
        lineEdit_91->setObjectName(QStringLiteral("lineEdit_91"));
        lineEdit_91->setGeometry(QRect(900, 140, 31, 27));
        lineEdit_91->setLayoutDirection(Qt::RightToLeft);
        lineEdit_91->setMaxLength(1);
        lineEdit_91->setReadOnly(true);
        lineEdit_261 = new QLineEdit(centralWidget);
        lineEdit_261->setObjectName(QStringLiteral("lineEdit_261"));
        lineEdit_261->setGeometry(QRect(870, 200, 31, 27));
        lineEdit_261->setLayoutDirection(Qt::RightToLeft);
        lineEdit_261->setMaxLength(1);
        lineEdit_261->setReadOnly(true);
        lineEdit_231 = new QLineEdit(centralWidget);
        lineEdit_231->setObjectName(QStringLiteral("lineEdit_231"));
        lineEdit_231->setGeometry(QRect(770, 200, 31, 27));
        lineEdit_231->setLayoutDirection(Qt::RightToLeft);
        lineEdit_231->setMaxLength(1);
        lineEdit_231->setReadOnly(true);
        lineEdit_631 = new QLineEdit(centralWidget);
        lineEdit_631->setObjectName(QStringLiteral("lineEdit_631"));
        lineEdit_631->setGeometry(QRect(900, 340, 31, 27));
        lineEdit_631->setLayoutDirection(Qt::RightToLeft);
        lineEdit_631->setMaxLength(1);
        lineEdit_631->setReadOnly(true);
        lineEdit_511 = new QLineEdit(centralWidget);
        lineEdit_511->setObjectName(QStringLiteral("lineEdit_511"));
        lineEdit_511->setGeometry(QRect(800, 300, 31, 27));
        lineEdit_511->setLayoutDirection(Qt::RightToLeft);
        lineEdit_511->setMaxLength(1);
        lineEdit_511->setReadOnly(true);
        lineEdit_581 = new QLineEdit(centralWidget);
        lineEdit_581->setObjectName(QStringLiteral("lineEdit_581"));
        lineEdit_581->setGeometry(QRect(740, 340, 31, 27));
        lineEdit_581->setLayoutDirection(Qt::RightToLeft);
        lineEdit_581->setMaxLength(1);
        lineEdit_581->setReadOnly(true);
        lineEdit_211 = new QLineEdit(centralWidget);
        lineEdit_211->setObjectName(QStringLiteral("lineEdit_211"));
        lineEdit_211->setGeometry(QRect(700, 200, 31, 27));
        lineEdit_211->setLayoutDirection(Qt::RightToLeft);
        lineEdit_211->setMaxLength(1);
        lineEdit_211->setReadOnly(true);
        lineEdit_571 = new QLineEdit(centralWidget);
        lineEdit_571->setObjectName(QStringLiteral("lineEdit_571"));
        lineEdit_571->setGeometry(QRect(700, 340, 31, 27));
        lineEdit_571->setLayoutDirection(Qt::RightToLeft);
        lineEdit_571->setMaxLength(1);
        lineEdit_571->setReadOnly(true);
        lineEdit_561 = new QLineEdit(centralWidget);
        lineEdit_561->setObjectName(QStringLiteral("lineEdit_561"));
        lineEdit_561->setGeometry(QRect(670, 340, 31, 27));
        lineEdit_561->setLayoutDirection(Qt::RightToLeft);
        lineEdit_561->setMaxLength(1);
        lineEdit_561->setReadOnly(true);
        lineEdit_751 = new QLineEdit(centralWidget);
        lineEdit_751->setObjectName(QStringLiteral("lineEdit_751"));
        lineEdit_751->setGeometry(QRect(700, 400, 31, 27));
        lineEdit_751->setLayoutDirection(Qt::RightToLeft);
        lineEdit_751->setMaxLength(1);
        lineEdit_751->setReadOnly(true);
        lineEdit_171 = new QLineEdit(centralWidget);
        lineEdit_171->setObjectName(QStringLiteral("lineEdit_171"));
        lineEdit_171->setGeometry(QRect(870, 170, 31, 27));
        lineEdit_171->setLayoutDirection(Qt::RightToLeft);
        lineEdit_171->setMaxLength(1);
        lineEdit_171->setReadOnly(true);
        lineEdit_11 = new QLineEdit(centralWidget);
        lineEdit_11->setObjectName(QStringLiteral("lineEdit_11"));
        lineEdit_11->setGeometry(QRect(640, 140, 31, 27));
        lineEdit_11->setLayoutDirection(Qt::RightToLeft);
        lineEdit_11->setMaxLength(1);
        lineEdit_11->setReadOnly(true);
        lineEdit_81 = new QLineEdit(centralWidget);
        lineEdit_81->setObjectName(QStringLiteral("lineEdit_81"));
        lineEdit_81->setGeometry(QRect(870, 140, 31, 27));
        lineEdit_81->setLayoutDirection(Qt::RightToLeft);
        lineEdit_81->setMaxLength(1);
        lineEdit_81->setReadOnly(true);
        lineEdit_161 = new QLineEdit(centralWidget);
        lineEdit_161->setObjectName(QStringLiteral("lineEdit_161"));
        lineEdit_161->setGeometry(QRect(840, 170, 31, 27));
        lineEdit_161->setLayoutDirection(Qt::RightToLeft);
        lineEdit_161->setMaxLength(1);
        lineEdit_161->setReadOnly(true);
        lineEdit_651 = new QLineEdit(centralWidget);
        lineEdit_651->setObjectName(QStringLiteral("lineEdit_651"));
        lineEdit_651->setGeometry(QRect(670, 370, 31, 27));
        lineEdit_651->setLayoutDirection(Qt::RightToLeft);
        lineEdit_651->setMaxLength(1);
        lineEdit_651->setReadOnly(true);
        lineEdit_611 = new QLineEdit(centralWidget);
        lineEdit_611->setObjectName(QStringLiteral("lineEdit_611"));
        lineEdit_611->setGeometry(QRect(840, 340, 31, 27));
        lineEdit_611->setLayoutDirection(Qt::RightToLeft);
        lineEdit_611->setMaxLength(1);
        lineEdit_611->setReadOnly(true);
        lineEdit_421 = new QLineEdit(centralWidget);
        lineEdit_421->setObjectName(QStringLiteral("lineEdit_421"));
        lineEdit_421->setGeometry(QRect(800, 270, 31, 27));
        lineEdit_421->setLayoutDirection(Qt::RightToLeft);
        lineEdit_421->setMaxLength(1);
        lineEdit_421->setReadOnly(true);
        lineEdit_361 = new QLineEdit(centralWidget);
        lineEdit_361->setObjectName(QStringLiteral("lineEdit_361"));
        lineEdit_361->setGeometry(QRect(900, 240, 31, 27));
        lineEdit_361->setLayoutDirection(Qt::RightToLeft);
        lineEdit_361->setMaxLength(1);
        lineEdit_361->setReadOnly(true);
        lineEdit_131 = new QLineEdit(centralWidget);
        lineEdit_131->setObjectName(QStringLiteral("lineEdit_131"));
        lineEdit_131->setGeometry(QRect(740, 170, 31, 27));
        lineEdit_131->setLayoutDirection(Qt::RightToLeft);
        lineEdit_131->setMaxLength(1);
        lineEdit_131->setReadOnly(true);
        lineEdit_621 = new QLineEdit(centralWidget);
        lineEdit_621->setObjectName(QStringLiteral("lineEdit_621"));
        lineEdit_621->setGeometry(QRect(870, 340, 31, 27));
        lineEdit_621->setLayoutDirection(Qt::RightToLeft);
        lineEdit_621->setMaxLength(1);
        lineEdit_621->setReadOnly(true);
        lineEdit_121 = new QLineEdit(centralWidget);
        lineEdit_121->setObjectName(QStringLiteral("lineEdit_121"));
        lineEdit_121->setGeometry(QRect(700, 170, 31, 27));
        lineEdit_121->setLayoutDirection(Qt::RightToLeft);
        lineEdit_121->setMaxLength(1);
        lineEdit_121->setReadOnly(true);
        lineEdit_281 = new QLineEdit(centralWidget);
        lineEdit_281->setObjectName(QStringLiteral("lineEdit_281"));
        lineEdit_281->setGeometry(QRect(640, 240, 31, 27));
        lineEdit_281->setLayoutDirection(Qt::RightToLeft);
        lineEdit_281->setMaxLength(1);
        lineEdit_281->setReadOnly(true);
        lineEdit_141 = new QLineEdit(centralWidget);
        lineEdit_141->setObjectName(QStringLiteral("lineEdit_141"));
        lineEdit_141->setGeometry(QRect(770, 170, 31, 27));
        lineEdit_141->setLayoutDirection(Qt::RightToLeft);
        lineEdit_141->setMaxLength(1);
        lineEdit_141->setReadOnly(true);
        lineEdit_481 = new QLineEdit(centralWidget);
        lineEdit_481->setObjectName(QStringLiteral("lineEdit_481"));
        lineEdit_481->setGeometry(QRect(700, 300, 31, 27));
        lineEdit_481->setLayoutDirection(Qt::RightToLeft);
        lineEdit_481->setMaxLength(1);
        lineEdit_481->setReadOnly(true);
        lineEdit_301 = new QLineEdit(centralWidget);
        lineEdit_301->setObjectName(QStringLiteral("lineEdit_301"));
        lineEdit_301->setGeometry(QRect(700, 240, 31, 27));
        lineEdit_301->setLayoutDirection(Qt::RightToLeft);
        lineEdit_301->setMaxLength(1);
        lineEdit_301->setReadOnly(true);
        lineEdit_111 = new QLineEdit(centralWidget);
        lineEdit_111->setObjectName(QStringLiteral("lineEdit_111"));
        lineEdit_111->setGeometry(QRect(670, 170, 31, 27));
        lineEdit_111->setLayoutDirection(Qt::RightToLeft);
        lineEdit_111->setMaxLength(1);
        lineEdit_111->setReadOnly(true);
        lineEdit_531 = new QLineEdit(centralWidget);
        lineEdit_531->setObjectName(QStringLiteral("lineEdit_531"));
        lineEdit_531->setGeometry(QRect(870, 300, 31, 27));
        lineEdit_531->setLayoutDirection(Qt::RightToLeft);
        lineEdit_531->setMaxLength(1);
        lineEdit_531->setReadOnly(true);
        lineEdit_791 = new QLineEdit(centralWidget);
        lineEdit_791->setObjectName(QStringLiteral("lineEdit_791"));
        lineEdit_791->setGeometry(QRect(840, 400, 31, 27));
        lineEdit_791->setLayoutDirection(Qt::RightToLeft);
        lineEdit_791->setMaxLength(1);
        lineEdit_791->setReadOnly(true);
        lineEdit_721 = new QLineEdit(centralWidget);
        lineEdit_721->setObjectName(QStringLiteral("lineEdit_721"));
        lineEdit_721->setGeometry(QRect(900, 370, 31, 27));
        lineEdit_721->setLayoutDirection(Qt::RightToLeft);
        lineEdit_721->setMaxLength(1);
        lineEdit_721->setReadOnly(true);
        label_2 = new QLabel(centralWidget);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(750, 100, 81, 21));
        label_2->setFrameShape(QFrame::WinPanel);
        label_3 = new QLabel(centralWidget);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(470, 510, 67, 17));
        label_4 = new QLabel(centralWidget);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(560, 510, 67, 17));
        pushButton = new QPushButton(centralWidget);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(600, 460, 99, 27));
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1007, 25));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);
        toolBar = new QToolBar(MainWindow);
        toolBar->setObjectName(QStringLiteral("toolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, toolBar);
        toolBar_2 = new QToolBar(MainWindow);
        toolBar_2->setObjectName(QStringLiteral("toolBar_2"));
        MainWindow->addToolBar(Qt::TopToolBarArea, toolBar_2);
        toolBar_3 = new QToolBar(MainWindow);
        toolBar_3->setObjectName(QStringLiteral("toolBar_3"));
        MainWindow->addToolBar(Qt::TopToolBarArea, toolBar_3);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", 0));
        label->setText(QApplication::translate("MainWindow", "SUDOKU", 0));
        go_pushbutton->setText(QApplication::translate("MainWindow", "Go!", 0));
        label_2->setText(QApplication::translate("MainWindow", "SOLUTION", 0));
        label_3->setText(QString());
        label_4->setText(QString());
        pushButton->setText(QApplication::translate("MainWindow", "next", 0));
        toolBar->setWindowTitle(QApplication::translate("MainWindow", "toolBar", 0));
        toolBar_2->setWindowTitle(QApplication::translate("MainWindow", "toolBar_2", 0));
        toolBar_3->setWindowTitle(QApplication::translate("MainWindow", "toolBar_3", 0));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
